// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReproIVF.WebAPI.Data;

#nullable disable

namespace ReproIVF.WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214015106_AddUsersAuth")]
    partial class AddUsersAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReproIVF.Shared.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.Bull", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Bulls");
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EmbryoCount")
                        .HasColumnType("int");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProgramId");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.Implant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BullId")
                        .HasColumnType("int");

                    b.Property<int?>("DonorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FertDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FreezingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ImplantDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("InCalf")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OpuDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("PreservationMethodId")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.Property<string>("RecipId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SemenTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("StrawId")
                        .HasColumnType("int");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BullId");

                    b.HasIndex("DonorId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PreservationMethodId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("SemenTypeId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("Implants");
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.PreservationMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PreservationMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fresh"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vit"
                        });
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.SemenType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SemenTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "conv"
                        },
                        new
                        {
                            Id = 2,
                            Name = "sex"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Empty"
                        });
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.Donor", b =>
                {
                    b.HasOne("ReproIVF.Shared.Entities.Program", "Program")
                        .WithMany("Donors")
                        .HasForeignKey("ProgramId");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.Implant", b =>
                {
                    b.HasOne("ReproIVF.Shared.Entities.Bull", "Bull")
                        .WithMany("Implants")
                        .HasForeignKey("BullId");

                    b.HasOne("ReproIVF.Shared.Entities.Donor", "Donor")
                        .WithMany("Implants")
                        .HasForeignKey("DonorId");

                    b.HasOne("ReproIVF.Shared.Entities.Client", "Owner")
                        .WithMany("Implants")
                        .HasForeignKey("OwnerId");

                    b.HasOne("ReproIVF.Shared.Entities.PreservationMethod", "PreservationMethod")
                        .WithMany("Implants")
                        .HasForeignKey("PreservationMethodId");

                    b.HasOne("ReproIVF.Shared.Entities.Program", "Program")
                        .WithMany("Implants")
                        .HasForeignKey("ProgramId");

                    b.HasOne("ReproIVF.Shared.Entities.SemenType", "SemenType")
                        .WithMany("Implants")
                        .HasForeignKey("SemenTypeId");

                    b.HasOne("ReproIVF.Shared.Entities.Technician", "Technician")
                        .WithMany("Implants")
                        .HasForeignKey("TechnicianId");

                    b.Navigation("Bull");

                    b.Navigation("Donor");

                    b.Navigation("Owner");

                    b.Navigation("PreservationMethod");

                    b.Navigation("Program");

                    b.Navigation("SemenType");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.Bull", b =>
                {
                    b.Navigation("Implants");
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.Client", b =>
                {
                    b.Navigation("Implants");
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.Donor", b =>
                {
                    b.Navigation("Implants");
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.PreservationMethod", b =>
                {
                    b.Navigation("Implants");
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.Program", b =>
                {
                    b.Navigation("Donors");

                    b.Navigation("Implants");
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.SemenType", b =>
                {
                    b.Navigation("Implants");
                });

            modelBuilder.Entity("ReproIVF.Shared.Entities.Technician", b =>
                {
                    b.Navigation("Implants");
                });
#pragma warning restore 612, 618
        }
    }
}
